version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase-if-necessary"
    groups:
      # Storybook dependencies should all have the same version, an older
      # version of storybook will complain about @storybook/* versions if
      # these lag behind
      storybook:
        patterns:
          - "@storybook/*"
          - "storybook"
    open-pull-requests-limit: 20
    reviewers:
      - "nl-design-system/kernteam-dependabot"
